version: "3.8"

services:
    postgres:
        image: postgres:latest
        container_name: cosc_301_proj_postgres_1
        environment:
            POSTGRES_PASSWORD: other_pw
            POSTGRES_DB: financial_data
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql #saved changes for postgres using volumes.
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql #runs init.sql

volumes:
    pgdata:
